name: cm_movies
description: CM Movies App
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.2
  dio: ^5.4.0
  path_provider: ^2.1.2
  flutter_dotenv: ^5.1.0
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/
    - .env
