name: Flutter Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.5' # လက်ရှိ stable version တစ်ခုကို သတ်မှတ်ပေးလိုက်ပါမယ်

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        # Gradle ပြဿနာကို ကျော်ဖြတ်ဖို့ build command ကို ပြင်လိုက်ပါတယ်
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
