name: Flutter Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3 ကို v4 ပြောင်းလိုက်တယ်

      - name: Setup Java
        uses: actions/setup-java@v4 # v3 ကို v4 ပြောင်းလိုက်တယ်
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4 # အခု Error တက်နေတဲ့ နေရာကို v4 ပြောင်းလိုက်ပါပြီ
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
